<a href="https://colab.research.google.com/github/mathewgit/Machine-Learning/blob/main/Machine-Learning/Codebasics/04_Saving_a_trained_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df=pd.read_csv("/content/drive/MyDrive/Data Science/Machine Learning/Code Basics/House Price.csv")

In [3]:
df # Simple Regression with one variable, Price depended on area

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [19]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [20]:
model.coef_




array([135.78767123])

In [21]:
model.intercept_

180616.43835616432

In [22]:
model.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])

In [23]:
#Save Model To a File Using Python Pickle # Allows to searlise Python Object to a file
with open('model_pickle','wb') as file:   # WB mean write binary data # This is basically a save state of mind
    pickle.dump(model,file)

In [24]:
#Load Saved Model
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [25]:
mp.coef_

array([135.78767123])

In [26]:
mp.intercept_

180616.43835616432

In [30]:
mp.predict([[6000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([995342.46575342])

In [32]:
import joblib


In [38]:
# Save Trained Model Using joblib
joblib.dump(model, 'model_joblib')

['model_joblib']

In [41]:
#Load Saved Model
mj = joblib.load('model_joblib')

In [42]:
mj.coef_

array([135.78767123])

In [43]:
mj.intercept_

180616.43835616432

In [44]:
mj.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])